### ISSUE TITLE
Standardize colors in legends

### ISSUE THREAD

**Issue by eriliawu** [Brian-Elbel-s-Research-Projects/project-overview#26]
Standardize colors for sub-group analysis. i.e. make sure colors in the by-group analysis are consistent across different analysts’ project. (we can talk about this in our Monday morning meeting)

**Comment by EmilHafeez** [comment]
https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html ?

**Comment by EmilHafeez** [comment]
please see template code change below.

Replace
 
`scale_color_manual(name="Open Time \nAfter Labeling", labels=c("12","15","18","21","24","27","30"),
                     values=c("hotpink","olivedrab3","red","orange","grey","purple","#13B0E4")) +`
 
with
 
`scale_color_viridis(discrete=TRUE, option="turbo",labels = c("Lunch (11:00-13:59)",
                              "Afternoon (14:00-16:59)",
                              "Dinner (17:00-20:59)",
                              "Evening (21:00-23:59)")) +
  guides(col=guide_legend("turbo"),
         size=guide_legend("turbo")) +
`

**Comment by eriliawu** [comment]
- For meal time
  - keep lunch, afternoon, dinner and evening in the figures
  - keep all 6 meal time categories in the table reporting
- macro nutrients
  - ordering: carb, protein, fat, sugar, sat fat, fiber, sodium
- item category:
  - burrito, dessert, other entree, side, taco (beverage comes last if this category is included)

**Comment by eriliawu** [comment]
- covariate balance
  - CBPS, IPTW, unmatched

**Comment by kritisingh21** [comment]
this code (provided above in sample)  -> guides(col=guide_legend("turbo"), size=guide_legend("turbo")) -> results in the legend title being "turbo" so I changed it to "Food Category" for both instances which "fixes" (for a lack of a better word) the legend title....not sure if this correct, but please let me know!

**Comment by EmilHafeez** [comment]
Proposed solution to be discussed::

_________________________________
## create a named object where each category of the interesting variable is assigned a Hex color value from the viridis color palette

`ggplot_palette_named = setNames(object = scales::viridis_pal()(length(unique(trend$loc))), nm = unique(trend$loc))`

## use the object in the scale_color_manual `values` option into the ggplot script such that each named category gets the assigned Hex color

`scale_color_manual(name = "Locations (Restricted)", labels=c("California","Suffolk"), values = ggplot_palette_named) +`
_________________________________

However, this would mean naming a color palette for each of the graph types (since the variables of interest would change)

Stress testing this seems to show color stability across varying numbers of categories since it's a named list

@eriliawu

**Comment by EmilHafeez** [comment]
color_reference= as.data.frame(c(2,3,4,6,8))
colnames(color_reference) <- c("color_categories")
ggplot_palette_named = setNames(object = scales::viridis_pal()(length(unique(color_reference$color_categories))), nm = unique(color_reference$color_categories))
ggplot_palette_named=ggplot_palette_named[-6]
